version: '3.8'
services:
  postgres-user-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb-catalog:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      - "27018:27017"
    volumes:
      - mongodata_v3:/data/db
  
  postgres-booking-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: booking_service_db
    ports:
      - "5433:5432"  # Exposed on 5433 locally
    volumes:
      - pgdata_booking:/var/lib/postgresql/data


volumes:
  pgdata:
  mongodata_v2:
  mongodata_v3:
  pgdata_booking: